# Generated by Django 4.2.4 on 2023-08-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls_blog', '0003_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default='uncategorized', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='cat_name',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
