# Generated by Django 4.2.4 on 2023-08-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls_blog', '0006_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above to  read Blog', max_length=500),
        ),
    ]
